[theme]
primaryColor = "#ff6b6b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = true
enableXsrfProtection = true
maxMessageSize = 200

[client]
toolbarMode = "minimal"
showErrorDetails = true
